### ISSUE TITLE
Get rid of Google Font

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/niara#1]
Niara theme includes [Raleway](https://github.com/thirtybees/niara/blob/cad62d91b09cc2db3bb145b996b3a8a9938ec2da/header.tpl#L69) font from google. While it works, it's not ideal for default theme. We should either:

1. Replace `Raleway` font with some common font
2. Include this font into asset folder

Note: if we opt for solution #2 then we should use [gulp-google-webfont](https://www.npmjs.com/package/gulp-google-webfonts) utility

**Comment by therampagerado** [comment]
This font does not have Cyrillic which will cause issues if there's no easy way to update it with one which has.

**Comment by Zengraph** [comment]
I propose to remomve totaly Raleway Gfont loading from the header and remove it also on the global.css file, instead let's just have : 
body {  font-family: Helvetica, Arial, sans-serif; } or Just Arial if you prefer.
Then, maybe one day the module thememaster I am working in mmaybe used and from that you'll be able to choose any popular Google font. For now I use a google font file generated by their api but not downloaded by the momdule directly.. that can be improve if needed, and if the customer wants to download and store the font on the hosting he just need to select that option from the module (still need to be added).

**Comment by TrueXakeP** [comment]
> 
> 
> This font does not have Cyrillic which will cause issues if there's no easy way to update it with one which has.

This font is Cyrillic, but only in version 4020, which after 6 years is still listed as beta (and have no updates at all https://github.com/impallari/Raleway), so I used fonttools/ttx as described in [this article](http://www.fontgeek.net/blog/?p=343) to rename it and use in our shop. So it is possible.

But personally, I like the approach used on many popular websites, using a lot of user's system fonts. Less weight, higher speed, no FOUT, native and familiar look. So I will use it next.

Something like this:
```css
body {
    font-family: -apple-system, BlinkMacSystemFont,
    "Segoe UI", Roboto, Helvetica, Arial, sans-serif,
    "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol".
}
```
