### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/niara#13]
I installed a fresh TB110 with the Niara theme. 

Then I noticed that the New Products module gave an image not found error. When I looked closer I found that the shop was  trying to load 17-medium_default/thee.jpg. When I looked in the images page of the back office I found that all image formats there start with Niara-. That means that there isn't any normal "medium-default".

This problem might happen with other modules too.

**Comment by Zengraph** [comment]
Corrected here by @Traumflug  : https://github.com/thirtybees/niara/commit/dd798ad52c103c9e97bd7cf1b0f2bc910f084b27

**Comment by Traumflug** [comment]
Actually it was the previous commit, df3c7f79af47ba7dde4454c990d041cc096722f8. Nevertheless thanks for pointing this out.

As always, if the problem persists in some situations despite of this fix, please don't hesitate to re-open this issue.
