### ISSUE TITLE
Tabs on the front page don't work right

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/niara#2]
There are three tabs, _New arrivals_, _Popular_ and _Best sellers_.

- Clicking on _Popular_ apparently does nothing.
- Clicking on _Best sellers_ removes the part above _Our featured products_ and appends best sellers below this section, without heading. Which then looks like no best sellers, but twice as many featured products.

**Comment by Dh42** [comment]
They should be working now. I am going to close this, I am going to commit using rows instead of tabs on the home page as well. Just to keep it cleaner and more modern.
