### ISSUE TITLE
Availability status

### ISSUE THREAD

**Issue by M4ketech** [thirtybees/niara#34]
By default availability status is hidden.

This can fixed with small tweeking code and using: https://github.com/ksimunovic/niara/commit/fbb993fdcfecd4579a6cbc3922354976beed92fb

**Comment by getdatakick** [comment]
I agree that availability should be displayed by default. It's probably much more easier for merchants to hide it (via css or by direct template edit) then to figure out how to show it.

**Comment by getdatakick** [comment]
Fixed by commit eddb7661e611f9f4f494449eec0cea134c0c884d. Thanks for the contribution
