### ISSUE TITLE
Can't translate button's string

### ISSUE THREAD

**Issue by wartinw** [thirtybees/niara#38]
in /niara/blob/master/modules/beesblogrecentposts/views/templates/hooks/home.tpl
Line 51 is:
							`<p><a class="btn btn-primary" href="{$post->link|escape:'htmlall':'UTF-8'}" title="{$post->title|escape:'htmlall':'UTF-8'}">Read More</a></p>`

but should be:
                                                       `<p><a class="btn btn-primary" href="{$post->link|escape:'htmlall':'UTF-8'}" title="{$post->title|escape:'htmlall':'UTF-8'}">{l s='Read More' mod='beesblogrecentposts'}</a></p>`

In /niara/blob/master/modules/beesblogrelatedproducts/views/templates/hooks/product.tpl

Line 42 is:
                   `     <p><a class="btn btn-primary" href="{$post.link|escape:'htmlall':'UTF-8'}" title="{$post.title|escape:'htmlall':'UTF-8'}">Read More</a></p>`

Should be:
                       ` <p><a class="btn btn-primary" href="{$post.link|escape:'htmlall':'UTF-8'}" title="{$post.title|escape:'htmlall':'UTF-8'}">{l s='Read More' mod='beesblogrelatedproducts'}</a></p>`

Same in these files:
beesblogpopularposts/views/templates/hooks/home.tpl
beesblogpopularposts/views/templates/hooks/product.tpl
beesblogrecentposts/views/templates/hooks/product.tpl

**Comment by wartinw** [comment]
Hi. I was trying to make a branch, fix the code and make a pull request. Could you give permission? Is it possible?
Thanks!

**Comment by getdatakick** [comment]
You need to fork the repository first. Then commit and push your changes to your repository. After that, you can go to original/this repository and create pull request from your repo.

No permissions needed.

**Comment by wartinw** [comment]
Thanks, I did it that way.
