### ISSUE TITLE
Radio buttons dont work to pick carriers

### ISSUE THREAD

**Issue by SLiCK-303** [thirtybees/niara#5]
As the title says.  When you checkout, with more that one carrier, you have to pick the carriers logo, not the radio buttons.  The radio buttons you cant click on.

**Comment by Dh42** [comment]
This one should fix that, https://github.com/thirtybees/niara/commit/38aff5428989d485ef4bdfd3ca08129128e8e5f7  

I wrapped the inputs in labels as well.

**Comment by SLiCK-303** [comment]
It's fixed.....nice job as always

**Comment by cienislaw** [comment]
what about advanced and opc-advanced?

**Comment by Traumflug** [comment]
If you found another bug, or the same bug on another page, please open a new issue, along with a description. Comments added to closed issue get forgotten.
