### ISSUE TITLE
Invalid HTML generated due to strip_tags after truncate

### ISSUE THREAD

**Issue by WBNet-Wout** [thirtybees/niara#59]
Niara seems to do something like the following on various places:

https://github.com/thirtybees/niara/blob/eddb7661e611f9f4f494449eec0cea134c0c884d/modules/beesblogrecentposts/views/templates/hooks/home.tpl#L49

This can cause it to generate for example the following invalid HTML:

```html
<p> Misschien heeft u gezien dat wij  spanningsgestuurde  en <a...</p>
```

As you can see, it generated an unclosed tag, i.e. `<a` in this example. To prevent this, you can call `strip_tags` first and afterwards call `truncate`, like the following:

```smarty
<p>{$post->content|strip_tags:false|truncate:150}</p>
```

**Comment by getdatakick** [comment]
Closed by e8e7e46f18f5ff1b52df67b27382058be8af8537. Thanks for reporting this issue
