### ISSUE TITLE
Merchandise return: checkboxes not visible

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/niara#6]
## Steps to reproduce:

1) enable returns in Back Office > Orders > Merchandise Returns
2) go to My Account > Order History
3) select order for which returns should be available

### Expected result:

List of products should display checkboxes to select products for return

### Actual result:

Checkboxes are rendered, but are not visible and accessible for selection

<img width="1393" alt="Order history - thirtybees 2019-07-12 07-00-55" src="https://user-images.githubusercontent.com/34651851/61103592-ebc08300-a472-11e9-80a5-2c1048229dea.png">

**Comment by SLiCK-303** [comment]
Dont know if I'm doing anything wrong, but when I apply @yaniv14 fix, I get this..which is close, but missing the top checkbox, and would look better if all checkboxes were centered in the cell.
![new](https://user-images.githubusercontent.com/763426/68090326-0bbbee00-fe38-11e9-9253-29c210cee1e8.PNG)

compared to community theme....
![old](https://user-images.githubusercontent.com/763426/68090327-15ddec80-fe38-11e9-84bb-e387a9ab9712.PNG)

**Comment by getdatakick** [comment]
I've picked @yaniv14 changes into master + I've added missing top checkbox, css alignment
